apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.1
        args: ["start-dev"] # Start Keycloak in development mode
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin" # Admin username
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin" # Admin password
        ports:
        - containerPort: 8080 # Internal Keycloak port
        resources: # Optional: Resource limits
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"

