apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880 
        env:
        - name: NODE_RED_USERNAME
          value: "admin"
        - name: NODE_RED_PASSWORD
          value: "admin"
        - name: KEYCLOAK_AUTH_URL
          value: "http://172.23.9.159:30080/auth"
        - name: KEYCLOAK_REALM
          value: "iot-realm"
        - name: KEYCLOAK_CLIENT_ID
          value: "node-red"
        volumeMounts:
        - name: node-red-data
          mountPath: /data
      volumes:
      - name: node-red-data
        emptyDir: {} # Use a PersistentVolumeClaim for production
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  selector:
    app: node-red
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 31880

