apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880 
        volumeMounts:
        - name: node-red-data
          mountPath: /data
      volumes:
      - name: node-red-data
        emptyDir: {} # Use a PersistentVolumeClaim for production
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  selector:
    app: node-red
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 31880

