apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31672
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30518
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30938

